### ISSUE TITLE
GooglePay and Music app getting deleted

### ISSUE THREAD

**Issue by Manu2456** [realKarthikNair/realme-ui-debloater#6]
During Debloating, the built in music app, video player and GooglePay is also lost. I think GooglePay was an out of the box app, but nonetheless it was useful. It would be great if you could allow us to keep those three apps.

ps: Waste apps like theme store, game centre, game space, Youtube music was still there after debloating. There maybe some people who uses these app, but me personally hate them. Which bring my second request, of adding a toggle or something to select which apps to keep and which to delete. Thanking you in advance.

**Comment by realKarthikNair** [comment]
I have fixed the first request, i.e. not removing `com.google.android.apps.nbu.paisa.user`, `com.heytap.music` and `com.coloros.video` in ffda31ceeb7f21f9c118fd6afde45928f73e8e71

Regarding manually keeping a checklist/toggle for specific apps, I'll probably implement that next month.

**By the way, Game Centre and Game Space should be removed with care since re-installling them isn't possible on several devices due to a bug in realme UI**

Please refer to the [latest version](https://realkarthiknair.live/realme-ui-debloater/releases.html) for updated script

Thank you for making realme-ui-debloater better!

**Comment by realKarthikNair** [comment]
Feature request moved as a separate issue. See #7
